In [1]:
import numpy as np
import pandas as pd
list=[[1,'Smith',50000],[2,'Jones',60000]]
df=pd.DataFrame(list)
df

   0      1      2
0  1  Smith  50000
1  2  Jones  60000

In [2]:
df.columns=['Empd','Name','Salary']
df

   Empd   Name  Salary
0     1  Smith   50000
1     2  Jones   60000

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Empd    2 non-null      int64
 1   Name    2 non-null      str
 2   Salary  2 non-null      int64
dtypes: int64(2), str(1)
memory usage: 112.0 bytes

In [4]:
df=pd.read_csv("50_Startups.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     str
 4   Profit           50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 1.8 KB

In [5]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [6]:
df.tail()

    R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [9]:
import numpy as np
import pandas as pd
df=pd.read_csv("employee.csv")
df.head()

   emp id                  name  salary
0       1     SREE VARSSINI K S    5000
1       2           SREEMATHI B    6000
2       3               SREYA G    7000
3       4  SREYASKARI MULLAPUDI    5000
4       5         SRI AKASH U G    8000

In [10]:
df.tail()

   emp id                   name  salary
2       3                SREYA G    7000
3       4   SREYASKARI MULLAPUDI    5000
4       5          SRI AKASH U G    8000
5       6  SRI HARSHAVARDHANAN R    3000
6       7  SRI HARSHAVARDHANAN R    6000

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   emp id  7 non-null      int64
 1   name    7 non-null      str
 2   salary  7 non-null      int64
dtypes: int64(2), str(1)
memory usage: 212.0 bytes

In [12]:
df.salary

0    5000
1    6000
2    7000
3    5000
4    8000
5    3000
6    6000
Name: salary, dtype: int64

In [13]:
type(df.salary)

pandas.Series

In [14]:
df.salary.mean()

np.float64(5714.285714285715)

In [15]:
df.salary.median()

np.float64(6000.0)

In [16]:
df.salary.mode()

0    5000
1    6000
Name: salary, dtype: int64

In [17]:
df.salary.var()

np.float64(2571428.5714285714)

In [18]:
df.salary.std()

np.float64(1603.5674514745463)

In [19]:
df.describe()

         emp id       salary
count  7.000000     7.000000
mean   4.000000  5714.285714
std    2.160247  1603.567451
min    1.000000  3000.000000
25%    2.500000  5000.000000
50%    4.000000  6000.000000
75%    5.500000  6500.000000
max    7.000000  8000.000000

In [20]:
df.describe(include='all')

          emp id                   name       salary
count   7.000000                      7     7.000000
unique       NaN                      6          NaN
top          NaN  SRI HARSHAVARDHANAN R          NaN
freq         NaN                      2          NaN
mean    4.000000                    NaN  5714.285714
std     2.160247                    NaN  1603.567451
min     1.000000                    NaN  3000.000000
25%     2.500000                    NaN  5000.000000
50%     4.000000                    NaN  6000.000000
75%     5.500000                    NaN  6500.000000
max     7.000000                    NaN  8000.000000

In [21]:
empCol=df.columns
empCol

Index(['emp id', 'name', 'salary'], dtype='str')

In [22]:
emparray=df.values
emparray

array([[1, 'SREE VARSSINI K S', 5000],
       [2, 'SREEMATHI B', 6000],
       [3, 'SREYA G', 7000],
       [4, 'SREYASKARI MULLAPUDI', 5000],
       [5, 'SRI AKASH U G', 8000],
       [6, 'SRI HARSHAVARDHANAN R', 3000],
       [7, 'SRI HARSHAVARDHANAN R', 6000]], dtype=object)

In [23]:
employee_DF=pd.DataFrame(emparray,columns=empCol)
employee_DF

  emp id                   name salary
0      1      SREE VARSSINI K S   5000
1      2            SREEMATHI B   6000
2      3                SREYA G   7000
3      4   SREYASKARI MULLAPUDI   5000
4      5          SRI AKASH U G   8000
5      6  SRI HARSHAVARDHANAN R   3000
6      7  SRI HARSHAVARDHANAN R   6000